server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据源名称
    name: defaultDataSource
    # 数据库连接地址
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:eladmin}?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: ${DB_USER:root}
    password: ${DB_PWD:root}
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 0
    host: ${REDIS_HOST:localhost} #生产环境修改
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        max-wait: -1
    timeout: 1000
logging:
  level:
    love.huhu.platform: debug
swagger:
  enabled: true
#jwt
jwt:
  header: Authorization
  # 令牌前缀
  token-start-with: Bearer
  # 必须使用最少88位的Base64对该令牌进行编码
  base64-secret: ZmQ0ZGI5NjQ0MDQwY2I4MjMxY2Y3ZmI3MjdhN2ZmMjNhODViOTg1ZGE0NTBjMGM4NDA5NzYxMjdjOWMwYWRmZTBlZjlhNGY3ZTg4Y2U3YTE1ODVkZDU5Y2Y3OGYwZWE1NzUzNWQ2YjFjZDc0NGMxZWU2MmQ3MjY1NzJmNTE0MzI=
  # 令牌过期时间 此处单位/秒 ，默认4小时，可在此网站生成 https://www.convertworld.com/zh-hans/time/milliseconds.html
  token-validity-in-seconds: 14400
  # 在线用户key
  online-key: online-token-
  # 验证码
  code-key: code-key-
  # token 续期检查时间范围（默认30分钟，单位毫秒），在token即将过期的一段时间内用户操作了，则给用户的token续期
  detect: 1800000
  # 续期时间范围，默认1小时，单位毫秒
  renew: 3600000
  skipToken: false
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
verify:
  private-key: "MIICdQIBADANBgkqhkiG9w0BAQEFAASCAl8wggJbAgEAAoGBAIeqJAHN9/Bf0f9076AWoI8LUOuehgkPz4QPqIJHLSoaPheNoIWzI/+v2S7XFZ1c6JelHiS0YFDazYdSyu1VLf+1rsHBZocQ4bA9+Ts8Xm2CO87BHTRsgVd2duHskmJo9CZ5rkvT5Xg68/iyXDxTP+J76HCjE1I4CsFC8EtEVm7ZAgMBAAECgYA/krxS2CkizFRFCJAuDcxpm9zsvRmEb5NICGpnumDwxOFp+iVJ4fuxmr8Ekyf+2QXp4idw/dHQsef0TRjpBKyL24KCDcF5yYPNGbR7bwcBsFEfmvkxNTbdzx50HLJWJLfL1Shd0l1EW277NJYj5Enxwm46CTBMDn3TEvMFr7mZsQJBAP4STRebqdilE/vt1XEhnUBUhJqbjdpr89cwZrumAckMwsNW178mc2iG965sL8JrkKPS1MgQMNUB1PwvWn9yrc0CQQCIscHb0cDYQxcqLsPiRiKg/cFVo3vr4l2cuO3yz0uVrSaz/2LabafY5DvLZs4NW+AsoD7br0U9pD0eXbTFMhk9AkAI7Z216atzSIHGRZpNim/bNd0fDb5TYZ3E/xdtGq1PYlppwOB+ABzoHG4RvA2FmIARsbP2f9MneRQB9KwKdH41AkBv6mGW8QfbyCo6HinAo72MY9YboItAGIieXQZsau4ucKKkcm7j+S2YNV0Dbns7ksJapyRvxvOAwWxM5VmwrhDdAkBx/IIebU4oZglKTnH2XRESP6udbiw/CAoWX9s6vcq4YTzEGJHF5VH6dkaaMBNyoAzUaunnyBsAhhjl5bcWQhGM"
  public-key: "MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANL378k3RiZHWx5AfJqdH9xRNBmD9wGD\n2iRe41HdTNF8RUhNnHit5NpMNtGL0NPTSSpPjjI1kJfVorRvaQerUgkCAwEAAQ=="

api:
  manager-server: http://localhost:8000
system:
  username: system
  password: system
#yml变量
#数据库
DB_HOST: localhost
#DB_PORT: 3306
#DB_USER: root
#DB_PWD: root
REDIS_HOST: localhost
